### ISSUE TITLE
Online Shop Bug in Microweber 1.3.2

### ISSUE THREAD

**Issue by AnimateDread** [microweber/microweber#1005]
I am experiencing an issue with the online shop functionality in Microweber 1.3.2. Specifically, in the "Settings > General" section, the online shop option has a blank rectangle below it. Additionally, in the "Settings > Advanced" section, when clicking on "Shop Settings," a blank popup titled Shop Settings appears.

Steps to Reproduce:

Run Microweber One Click Install on a Digital Ocean droplet. OS : Ubuntu 20.04.5 LTS.
Navigate to the "Settings > General" section.
Observe the blank rectangle below the online shop option.
Navigate to the "Settings > Advanced" section.
Click on "Shop Settings."
Observe the blank popup that appears.

Reproducibility:
This issue is reproducible on an installation of Microweber 1.3.2, but not on another identical Digital Ocean droplet with a different Microweber 1.3.2 website. System settings are the same on both instances.

Additional Information:
I have tried reinstalling Microweber using the standalone updater, clearing the cache, rebooting the server, and installing server updates without success. I am not experiencing this issue on another identical Digital Ocean droplet with a different Microweber 1.3.2 website. All modules and templates are up to date on both instances.

**Comment by AnimateDread** [comment]
[2023-03-02 14:54:22] production.ERROR: imagesx(): Argument #1 ($im>[stacktrace]
#0 /var/www/html/src/MicroweberPackages/Utils/ThirdPartyLibs/PHPIma>#1 /var/www/html/src/MicroweberPackages/Utils/Media/Thumbnailer.php>#2 /var/www/html/src/MicroweberPackages/Media/MediaManager.php(1101>#3 /var/www/html/src/MicroweberPackages/App/functions/api_callbacks>#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ca>#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ro>#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ro>#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ro>#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/P>#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/P>#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/R>#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/R>#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#16 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/I>#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#18 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.>#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#20 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(>#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/M>#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/M>#31 /var/www/html/src/MicroweberPackages/App/Http/Middleware/StartS>#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Mi>#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#41 /var/www/html/index.php(94): Illuminate\\Foundation\\Http\\Kern>#42 {main}                                                          "}                                                                  [2023-03-02 23:53:42] production.ERROR: imagesx(): Argument #1 ($im>
[stacktrace]
#0 /var/www/html/src/MicroweberPackages/Utils/ThirdPartyLibs/PHPIma>#1 /var/www/html/src/MicroweberPackages/Utils/Media/Thumbnailer.php>#2 /var/www/html/src/MicroweberPackages/Media/MediaManager.php(1101>#3 /var/www/html/src/MicroweberPackages/App/functions/api_callbacks>#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ca>#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ro>#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ro>#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ro>#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/P>#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/P>#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/R>#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/R>#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/R>#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/R>#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#16 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/I>#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#18 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.>#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#20 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(>#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/M>#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/M>#31 /var/www/html/src/MicroweberPackages/App/Http/Middleware/StartS>#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Mi>#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#41 /var/www/html/index.php(94): Illuminate\\Foundation\\Http\\Kern>#42 {main}
"}
[2023-03-03 00:00:14] production.ERROR: imagesx(): Argument #1 ($im>[stacktrace]
#0 /var/www/html/src/MicroweberPackages/Utils/ThirdPartyLibs/PHPIma>#1 /var/www/html/src/MicroweberPackages/Utils/Media/Thumbnailer.php>#2 /var/www/html/src/MicroweberPackages/Media/MediaManager.php(1101>#3 /var/www/html/src/MicroweberPackages/App/functions/api_callbacks>#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Ca>  GNU nano 4.8                laravel.log                           #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#16 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/I>#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#18 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.>#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#20 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(>#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/M>#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/M>#31 /var/www/html/src/MicroweberPackages/App/Http/Middleware/StartS>#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Mi>#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/>#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundatio>#41 /var/www/html/index.php(94): Illuminate\\Foundation\\Http\\Kern>#42 {main}

**Comment by peter-mw** [comment]
Hi, this error in the log may be related to an image you are uploading, its not related to the shop settings.

**Comment by AnimateDread** [comment]
Hi, I've provided the whole log file, this means that no errors where logged, but the shop issue is still very present.
