### ISSUE TITLE
Installing Templates from Marketplace

### ISSUE THREAD

**Issue by chlarsen** [microweber/microweber#352]
Dear All,

I seem to have a problem, when installing templates from marketplace. To keep the workflow simple, let's go for a free template ;-).
I am logged in as admin, click on Marketplace, and click on, for instance, Bootstrap 3.
Clicking on install yields a message on top of the screen saying: "Installing item", which disappears after a couple of seconds.
Let's reload the whole thing, clear the browser cache (and the reverse proxy cache, etc.), but there is no Bootstrap 3 template whatsoever.
The debug log says:
```
[2016-03-30 06:20:51] production.ERROR: exception 'ErrorException' with message 'is_dir(): open_basedir restriction in effect. File(/home/www_php/caocuero.com/microweber/userfiles/templates/bootstrap3/css/styles) is not within the allowed path(s): (/home/www_php/caocuero.com/microweber:/tmp:/usr/local/lib/php:/var/tmp)' in /home/www_php/caocuero.com/microweber/src/Microweber/Utils/Unzip.php:322
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'is_dir(): open_...', '/home/www_php/c...', 322, Array)
#1 /home/www_php/caocuero.com/microweber/src/Microweber/Utils/Unzip.php(322): is_dir('/home/www_php/c...')
#2 /home/www_php/caocuero.com/microweber/src/Microweber/Utils/Unzip.php(77): Microweber\Utils\Unzip->native_unzip('/home/www_php/c...', '/home/www_php/c...', true)
#3 /home/www_php/caocuero.com/microweber/src/Microweber/Providers/UpdateManager.php(650): Microweber\Utils\Unzip->extract('/home/www_php/c...', '/home/www_php/c...', true)
#4 /home/www_php/caocuero.com/microweber/src/Microweber/Providers/UpdateManager.php(195): Microweber\Providers\UpdateManager->install_from_market(Array)
#5 /home/www_php/caocuero.com/microweber/src/Microweber/functions/other.php(237): Microweber\Providers\UpdateManager->install_market_item(Array)
#6 /home/www_php/caocuero.com/microweber/src/Microweber/Controllers/DefaultController.php(476): mw_install_market_item(Array)
#7 [internal function]: Microweber\Controllers\DefaultController->api('mw_install_mark...')
#8 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#9 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('api', Array)
#10 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(Microweber\Controllers\DefaultController), Object(Illuminate\Routing\Route), 'api')
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Microweber\Controllers\DefaultController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'api')
#17 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), '\\Microweber\\Con...', 'api')
#18 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/Route.php(131): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#19 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Routing/Router.php(619): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\
Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /home/www_php/caocuero.com/microweber/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /home/www_php/caocuero.com/microweber/index.php(72): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#45 {main}
```
Hey, that is strange: It says:
```
[2016-03-30 06:20:51] production.ERROR: exception 'ErrorException' with message 'is_dir(): open_basedir restriction in effect. File(/home/www_php/caocuero.com/microweber/userfiles/templates/bootstrap3/css/styles) is not within the allowed path(s): (/home/www_php/caocuero.com/microweber:/tmp:/usr/local/lib/php:/var/tmp)' in /home/www_php/caocuero.com/microweber/src/Microweber/Utils/Unzip.php:322
```
However, my php-fpm.d pool configuration specifically says:
```
php_admin_value[open_basedir] = /home/www_php/caocuero.com/microweber:/tmp:/usr/local/lib/php:/var/tmp
```
For the fun of it, I commented out all disabled (potentially dangerous functions) as well as the basedir resitrction. Alas, no joy, again. Interestingly, PHP-FPM did not yield any errors, whatever the above debug said. Normally, it would through an error, if the opon_basedir directive got violated.
The above (incomplete) installation process did manage to download a UUID-named.zip file into microweber/storage/cache/updates_temp, but failed to create the boostrap3 directory in microwever/userfiles/templates/ properly. The only file in the bootstrap3 folder is an zero-length file called css. I have noted before with ShopMag, that not even a folder is created, but just a zero-length file called shopmag inside microweber/userfiles/templates.
Permissions are set to rwX for the PHP-FPM user, r-X to the Nginx with FastCGI user, with no access to others.
Manual installation by unzipping the downloaded file in microweber/storage/cache/updates_temp works, and the new template becomes usable.
Any thoughts?
Thank a lot!
Chris

**Comment by ash-rain** [comment]
@peter-mw I bet this has something to do with the issue from last night with Photon.

**Comment by chlarsen** [comment]
It does not only affect Photon, but all the templates, I am afraid.
Thanks a lot, Peter,
Chris

On 30/03/16 16:46, Ash wrote:
> @peter-mw <https://github.com/peter-mw> I bet this has something to do
> with the issue from last night with Photon.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/microweber/microweber/issues/352#issuecomment-203350896>
>

-- 
Dr Christoph H. Larsen
synaLinQ
296/33 Lương Định Của, Ngọc Hội 2, Vĩnh Ngọc
Nha Trang, Khanh Hoa, Vietnam
Mobile:	+84-98-9607357 (Vietnam)
	+254-770-632403 (Kenya)
	+256-790-527900 (Uganda)
	+49-176-96456254 (Germany)
Fax:	+49-231-292734790
E-mail:	christoph.larsen@synalinq.com
Skype:	christoph.larsen

**Comment by ash-rain** [comment]
Can you pleasy try downloading from https://microweber.com/marketplace and manually unzip in userfiles/templates

**Comment by chlarsen** [comment]
I have done this, and this works. I hope I have mentioned that in the 
bug report...
Chris

On 30/03/16 16:48, Ash wrote:
> Can you pleasy try downloading from https://microweber.com/marketplace
> and manually unzip in userfiles/templates
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/microweber/microweber/issues/352#issuecomment-203351357>
>

-- 
Dr Christoph H. Larsen
synaLinQ
296/33 Lương Định Của, Ngọc Hội 2, Vĩnh Ngọc
Nha Trang, Khanh Hoa, Vietnam
Mobile:	+84-98-9607357 (Vietnam)
	+254-770-632403 (Kenya)
	+256-790-527900 (Uganda)
	+49-176-96456254 (Germany)
Fax:	+49-231-292734790
E-mail:	christoph.larsen@synalinq.com
Skype:	christoph.larsen

**Comment by ash-rain** [comment]
It's probably temporary issue with our servers (resulting in timeout) but we need to change the download process anyway. This might take a while.

**Comment by chlarsen** [comment]
Actually, the download is fast: the .zip file DOES got downloaded, after 
all. It is the folder creation in the userfiles/templates folder that 
gets messed up, despite reasonable permissions.


On 30/03/16 16:51, Ash wrote:
> It's probably temporary issue with our servers (resulting in timeout)
> but we need to change the download process anyway. This might take a while.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/microweber/microweber/issues/352#issuecomment-203353560>
>

-- 
Dr Christoph H. Larsen
synaLinQ
296/33 Lương Định Của, Ngọc Hội 2, Vĩnh Ngọc
Nha Trang, Khanh Hoa, Vietnam
Mobile:	+84-98-9607357 (Vietnam)
	+254-770-632403 (Kenya)
	+256-790-527900 (Uganda)
	+49-176-96456254 (Germany)
Fax:	+49-231-292734790
E-mail:	christoph.larsen@synalinq.com
Skype:	christoph.larsen

**Comment by peter-mw** [comment]
thanks for report, will try to reproduce locally and fix

**Comment by chlarsen** [comment]
Thanks a lot, Peter, whenever you have a chance. Hugely appreciated. I 
keep that sandbox there, where it is :-).
