### ISSUE TITLE
Uncaught exception 'ReflectionException' with message 'Class log does not exist'

### ISSUE THREAD

**Issue by JobsLong** [microweber/microweber#363]
when i installed this project and run:

```
php artisan
```

The exception is here : 

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('log')
#1 /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('log', Array)
#2 /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->make('log', Array)
#3 /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Container/Container.php(887): Illuminate\Foundation\Application->make('Psr\Log\LoggerI...')
#4 /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Container/Container.php(848): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Conta in /home/projects/cms-demo/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 776
```

i had find some solutions through google, but still does not solve this problem, anyone has encountered same problem?

**Comment by peter-mw** [comment]
Strange... it works for me..

Can you tell me which PHP version are you using?

**Comment by peter-mw** [comment]
cant reproduce
