### ISSUE TITLE
Logo module config should allow selecting existing uploaded image

### ISSUE THREAD

**Issue by shchukax** [microweber/microweber#373]
Currently, the only way to specify an image for the logo module is to upload one.  There should be an option to select from already uploaded images or specify an external URL.

**Comment by Xarcell** [comment]
Where do you see this module? I do not see it.

**Comment by shchukax** [comment]
Just go to "add module" (top left in live edit mode) and search for "logo"

**Comment by Xarcell** [comment]
Ahhh, you mean in edit mode. Ok, thanks.

**Comment by shchukax** [comment]
@peter-mw I have code ready for this feature, however I developed it based on 1.0.7.  I wanted to create a pull request based on 1.0.8, but I can't 1.0.8 to run - I get the "whoops something went wrong" error and the error log contains the following:

    [Wed Dec 21 08:28:38 2016] [error] [client 5.148.17.52] PHP Fatal error:  Class 'Illuminate\\Routing\\ControllerServiceProvider' not found in /var/www/cms/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
    [Wed Dec 21 08:28:41 2016] [error] [client 5.148.17.52] PHP Fatal error:  Class 'Illuminate\\Routing\\ControllerServiceProvider' not found in /var/www/cms/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

**Comment by peter-mw** [comment]
hi @shchukax 

Can you replace the `config/app.php` or comment out [this line](https://github.com/microweber/microweber/blob/6557b3dbef2fd9d38581a6fedf43da4af574d45d/config/app.php#L128)

Also you need to add this file `config/auth.php` from 1.0.8 

let me know if it works

**Comment by shchukax** [comment]
Hi @peter-mw  Thanks for the reply.  I started by cloning the 1.0.8 branch.  I now commented out this line:

    'Illuminate\Routing\ControllerServiceProvider',

in `config\app.php`.  I do have `config\auth.php` in place, as well.  Now I get the following error in the laravel log:

````
[2016-12-21 15:08:23] production.ERROR: exception 'InvalidArgumentException' with message 'Auth guard [] is not defined.' in /var/www/cms/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:86
Stack trace:
#0 /var/www/cms/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(70): Illuminate\Auth\AuthManager->resolve(NULL)
#1 /var/www/cms/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(294): Illuminate\Auth\AuthManager->guard()
#2 /var/www/cms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\Auth\AuthManager->__call('check', Array)
#3 /var/www/cms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\Auth\AuthManager->check()
#4 /var/www/cms/src/Microweber/Providers/UserManager.php(253): Illuminate\Support\Facades\Facade::__callStatic('check', Array)
#5 /var/www/cms/src/Microweber/Providers/UserManager.php(253): Illuminate\Support\Facades\Auth::check()
#6 /var/www/cms/src/Microweber/functions/user.php(173): Microweber\Providers\UserManager->is_logged()
#7 /var/www/cms/src/Microweber/Controllers/DefaultController.php(243): is_logged()
#8 [internal function]: Microweber\Controllers\DefaultController->api('is_logged')
#9 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#10 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('api', Array)
#11 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(190): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Microweber\Controllers\DefaultController), 'api')
#12 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#13 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /var/www/cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/cms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/cms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/cms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/cms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/cms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /var/www/cms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#36 /var/www/cms/index.php(72): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#37 {main}  
````

**Comment by peter-mw** [comment]
hi, can you do a fresh clone of the 1.0.8 branch and after that `composer install` and it should run

then copy your module over the logo module

**Comment by peter-mw** [comment]
can you  set  `'debug' => true,`

in https://github.com/microweber/microweber/blob/1.0.8/config/app.php#L16 

and paste the error

**Comment by shchukax** [comment]
Here's what I get:

````
1/1 ErrorException in default.php line 17: Undefined variable: ratings

in default.php line 17
at HandleExceptions->handleError('8', 'Undefined variable: ratings', '/var/www/mednav.org/test/web/cms-1.0.8/userfiles/modules/rating/templates/default.php', '17', array('this' => object(View), 'v' => '/var/www/mednav.org/test/web/cms-1.0.8/userfiles/modules/logo/index.php', 'config' => array('path' => '/var/www/mednav.org/test/web/cms-1.0.8/userfiles/modules/logo/', 'mp' => '/var/www/mednav.org/test/web/cms-1.0.8/userfiles/modules/logo/', 'path_to_module' => '/var/www/mednav.org/test/web/cms-1.0.8/userfiles/modules/logo/', 'the_module' => 'logo', 'module' => 'logo', 'module_name' => '.', 'module_name_url_safe' => 'logo', 'url' => 'https://test.mednav.org/cms/', 'url_base' => 'https://test.mednav.org/cms/', 'url_main' => 'https://test.mednav.org/cms/', 'module_api' => 'https://test.mednav.org/cms/api/logo', 'module_view' => 'https://test.mednav.org/cms/module/logo', 'ns' => 'logo', 'module_class' => 'module-logo', 'url_to_module' => 'https://test.mednav.org/cms/userfiles/modules/logo/'), 'app' => object(Application), 'params' => array('data-class' => 'module module module-logo', 'class' => 'module module module-logo', 'mw-title' => 'Logo', 'data-mw-title' => 'Logo', 'type' => 'logo', 'data-type' => 'logo', 'data-id' => 'logo-20161221083405', 'id' => 'logo-20161221083405', 'module' => 'logo', 'parent-module' => 'logo', 'parent-module-id' => 'logo-20161221083405'), 'logotype' => 'image', 'logoimage' => 'https://test.mednav.org/cms/userfiles/media/test-mednav-org/uploaded/mednav_web_03_1.png', 'text' => false, 'font_family' => null, 'font_size' => '30', 'default' => '', 'font_family_safe' => 'inherit', 'template' => 'default')) in default.php line 17
at include('/var/www/mednav.org/test/web/cms-1.0.8/userfiles/modules/rating/templates/default.php') in index.php line 57
at include('/var/www/mednav.org/test/web/cms-1.0.8/userfiles/modules/logo/index.php') in View.php line 71
at View->__toString() in Parser.php line 1481
at Parser->load('logo', array('class' => 'module module module-logo', 'data-mw-title' => 'Logo', 'data-type' => 'logo', 'id' => 'logo-20161221083405')) in Parser.php line 448
at Parser->process('<!DOCTYPE HTML> <html prefix="og: http://ogp.me/ns#"> <head> <title>{content_meta_title}</title> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <meta property="og:title" content="{content_meta_title}" /> <meta name="keywords" content="{content_meta_keywords}" /> <meta name="description" content="{content_meta_description}" /> <meta property="og:type" content="{og_type}" /> <meta property="og:url" content="{content_url}" /> <meta property="og:image" content="{content_image}" /> <meta property="og:description" content="{og_description}" /> <meta property="og:site_name" content="{og_site_name}" /> <link rel="alternate" type="application/rss+xml" title="{og_site_name}" href="https://test.mednav.org/cms/rss" /> <link href='//fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'> <link href='//fonts.googleapis.com/css?family=Roboto+Slab:400,300&subset=latin,cyrillic,cyrillic-ext,greek,latin-ext' rel='stylesheet' type='text/css'> <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300italic&subset=latin,cyrillic,greek,latin-ext' rel='stylesheet' type='text/css'> <script type="text/javascript"> mw.lib.require("bootstrap3"); mw.require(mw.settings.template_url + "js/functions.js"); </script> <link rel="stylesheet" href="https://test.mednav.org/cms/userfiles/templates/liteness/css/style.css" type="text/css" /> <link rel="stylesheet" id="colorscss" href="https://test.mednav.org/cms/userfiles/templates/liteness/css/colors/default.css" type="text/css" /> <style id="customcolorscss" type="text/css">#header, #footer{background-color:#564A8F} {color:#564A8F} body{background-color:#D1F056} #mwnoop{color:#D1F056} .box-container, #main-menu{background-color:#F5F5F5} #mwnoop{color:#F5F5F5} .contact-form-template-dream .cft-submit, .contact-form-template-dark .cft-submit,.contact-form-template-dream .cft-submit:hover, .contact-form-template-dark .cft-submit:hover,.contact-form-template-dream .cft-submit:focus, .contact-form-template-dark .cft-submit:focus,.pagination > a.active, .mw-search-autocomplete .module-posts-template-search > ul > li.active,.btn-default, .btn-action, .product-price-holder .btn, .btn-action-default,.btn-default:hover, .btn-action:hover, .product-price-holder .btn:hover, .btn-action-default:hover,.btn-default:focus, .btn-action:focus, .product-price-holder .btn:focus, .btn-action-default:focus,.module-navigation-default li:hover > a, .module-navigation-default li a.active, .module-navigation-default li a.active:hover,.module-navigation-default a.active:active, .module-navigation-default a.active:focus,.module-navigation-default li:hover a, .module-navigation-default li a:hover, .module-navigation-default li a:focus,.module-navigation-default li:hover a.active, .module-navigation-default a.active,.module-navigation-default a.active:hover,.module-navigation-default a.active:active,.module-navigation-default a.active:focus,#header .pagination > a.active, #footer .pagination > a.active, .pagination > .active > a, .pagination > .active > span,.pages-nav-default li a:hover, .pages-nav-default li a:focus,.pagination > .active > a:hover, .pagination > .active > span:hover, .pagination > .active > a:focus, .pagination > .active > span:focus{background-color:#6D6DD1} .cart-small-checkout-link, .cart-small, .cart-small-checkout-link:hover, .cart-small-checkout-link:focus, .cart-small-checkout-link:active, .box-container a, #main-menu a, .sidebar a, .sidebar-box .nav li a{color:#6D6DD1} .box-container {padding: 20px; }.box-container .box-container{ padding: 0; } </style> <style id="custom_bg" type="text/css"></style> <style type="text/css"> .module-navigation-default li a.active, #header .module-navigation-default li a.active, .module-navigation-default li a:hover, .module-navigation-default li:hover a, #header .module-navigation-default li a:hover, #header .module-navigation-default li:hover a, .module-navigation-default li a:focus, #header .module-navigation-default li a:focus{ color: white; } </style></head> <body class=" "> <div id="main-container"> <div id="header"> <div class="container edit" field="liteness-header" rel="global"> <div class="row"> <div class="col-md-9"> <h1 class="edit element" id="logo" field="logo-top" rel="global"> <a href="https://test.mednav.org/cms/"> <span>Liteness</span> <small>Define your own Space</small> </a> </h1> </div> <div class="col-md-3"> <div class="header-cart"><module type="shop/cart" template="small"></div> </div> </div> </div> <div id="main-menu"> <div class="container"> <div class="row"> <div class="col-md-9"><module type="menu" /></div> <div class="col-md-3" id="header-search"><module type="search" template="autocomplete" /></div> </div> </div> </div> </div> <div id="content-holder"> <section id="content"> <div class="box-container"> <div class="container edit" field="content" rel="content"> <p class="element">Type your text here</p> </div> </div> </section> <div id="footer"> <div class="container"> <div class="mw-ui-row"> <div class="mw-ui-col" id="copyright"> <div class="edit" field="footer-left" rel="global"> <p class="element">Copyright &copy; All rights reserved</p> </div> </div> <div class="mw-ui-col" id="footer-menu"> <div class="edit" field="footer-right" rel="global"> <module type="menu" name="footer_menu" template="small"> </div> </div> <div class="mw-ui-col" id="powered"> <div><span class="mw-powered-by"><a href="https://microweber.com/" title="Create free Website &amp; Online Shop">Create Website</a> with <a href="https://microweber.com" target="_blank" title="Microweber CMS">Microweber</a></span></div> </div> </div> </div> </div> </div> </div> </body></html>', false) in DefaultController.php line 1697
at DefaultController->frontend() in DefaultController.php line 64
at DefaultController->index()
at call_user_func_array(array(object(DefaultController), 'index'), array()) in Controller.php line 55
at Controller->callAction('index', array()) in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(DefaultController), 'index') in Route.php line 190
at Route->runController() in Route.php line 144
at Route->run(object(Request)) in Router.php line 642
at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Router.php line 644
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 618
at Router->dispatchToRoute(object(Request)) in Router.php line 596
at Router->dispatch(object(Request)) in Kernel.php line 268
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
at Pipeline->then(object(Closure)) in Kernel.php line 150
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
at Kernel->handle(object(Request)) in index.php line 72
````

**Comment by peter-mw** [comment]
opps, sorry its from the module i added yesterday, i just pushed a fix  038c1018061ddcb58eeaa151712718c4f31551c8

can you pull and try again

**Comment by shchukax** [comment]
Thanks, it runs now.  Unfortunately, I can't edit a page - when I click on "edit" link, nothing happens.  I can go into live edit mode, but some functionality doesn't work any more.

Logo module as is does not work at all - when I try to add it to a page, nothing happens.  If I replace it with my modified one from 1.0.7, then it work, but it then looses the changes introduced in 1.0.8.

The only file I changed in the logo module has not changed from 1.0.7, therefore I submitted a pull request with 1.0.8 as it was at the time of my pull and containing that file.  I can't quite test whether these changes will work correctly on 1.0.8 though.

**Comment by peter-mw** [comment]
oops i forgot to mention  you will need make `compile_assets` to `false` in `config/microewer.php` in order to load the new JS

**Comment by shchukax** [comment]
That didn't help :(  Same results - logo not showing and clicking 'edit' on a page does nothing.  Checking further, I see a 500 error in the console:

POST to `/modules` resulting in 500 error (called from apijs.js) - but I don't see any errors in the server error log.  Here's the stack trace of the javascript call:

````
apijs:6 POST https://test.mednav.org/cms/module/ 500 (Internal Server Error)
send	@	apijs:6
ajax	@	apijs:6
jQuery.ajax	@	apijs:200
r.(anonymous function)	@	apijs:6
mw._	@	apijs:1012
mw.load_module	@	apijs:805
mw_set_edit_posts	@	view:content:746
(anonymous function)	@	view:content:672
hashParam	@	apijs:6897
hashParamEventInit	@	apijs:6920
(anonymous function)	@	apijs:7089
dispatch	@	apijs:5
q.handle	@	apijs:5
````

**Comment by peter-mw** [comment]
really strange, 

can you try to make new install on new db

**Comment by shchukax** [comment]
Ok, will do tomorrow and let you know.

**Comment by shchukax** [comment]
@peter-mw Just tried with a clean clone of 1.0.8 and a clean empty database - same result.  Logo module cannot be added to a page. A spinner is shown for a second - then disappears.  Nothing in the logs or in the browser console.

**Comment by peter-mw** [comment]
hi @shchukax 

i merged your commit

its working now 

![image](https://cloud.githubusercontent.com/assets/5698247/21423769/767ea680-c847-11e6-8c7c-a7ab11e59dd4.png)

**Comment by shchukax** [comment]
Great stuff! Glad to help.
