### ISSUE TITLE
fatal error: user_manager class missing (HTTP 500) after updating from 1.1.8

### ISSUE THREAD

**Issue by stuntsman** [microweber/microweber#656]
I've tried to update from 1.1.8 using the admin update screen, but after updating the website stopped working. The contents of version.txt were changed to 1.1.19.

I've found this in the error log:

```
[2020-06-22 13:11:39] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class user_manager does not exist in /storage/ww
w/aiweb.staging.dotsamazing.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /storage/www/aiweb.staging.dotsamazing.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('user_manager')
#1 /storage/www/aiweb.staging.dotsamazing.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('user_manager')
#2 /storage/www/aiweb.staging.dotsamazing.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('user_manager')
#3 /storage/www/aiweb.staging.dotsamazing.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('user_manager')
#4 /storage/www/aiweb.staging.dotsamazing.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(1172): Illuminate\Foundation\Application->make(' in /storage/ww
w/aiweb.staging.dotsamazing.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 {main}
```

After restoring the old files from backup the site is now working, I just can't update as this happens everytime. 

Is it ok if I install a fresh mw and simply restore the old database?

**Comment by peter-mw** [comment]
hi, sorry for your issue, 

this issue may be related to cache of the file `bootstrap/cache/services.php` , try deleting this file

also you can update manually

just download the master branch and replace folders `src` and `userfiles/modules`
