### ISSUE TITLE
docker-compose .htaccess permission denied

### ISSUE THREAD

**Issue by meesvw** [microweber/microweber#948]
I started the docker-compose with `sudo docker-compose up` and was met with this message when I try to visit the website:

console:
```bash
(13)Permission denied: [client REDACTED] AH00529: /var/www/html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/html/' is executable
```

browser:
```text
Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe
```

Steps I tried:
- chmod 644 recursive on the microweber folder
- adding the .htaccess individualy

If you need more information feel free to ask me.

**Comment by meesvw** [comment]
Update I managed by moving all the files to get the following error:
console:
```bash
[php:error] [pid 2814] [client REDACTED] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/bootstrap/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/index.php:63\nStack trace:\n#0 {main}\n  thrown in /var/www/html/index.php on line 63
```

website:
```text
Warning: require(/var/www/html/bootstrap/autoload.php): Failed to open stream: Permission denied in /var/www/html/index.php on line 63

Fatal error: Uncaught Error: Failed opening required '/var/www/html/bootstrap/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/index.php:63 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 63
```

**Updating the permissions of the `bootstraps` folder brings this error:**

console:
```bash
[php:error] [pid 2815] [client REDACTED] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bootstrap/autoload.php:17\nStack trace:\n#0 /var/www/html/index.php(63): require()\n#1 {main}\n  thrown in /var/www/html/bootstrap/autoload.php on line 17
```

website:
```text
Warning: require(/var/www/html/bootstrap/../vendor/autoload.php): Failed to open stream: Permission denied in /var/www/html/bootstrap/autoload.php on line 17

Fatal error: Uncaught Error: Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bootstrap/autoload.php:17 Stack trace: #0 /var/www/html/index.php(63): require() #1 {main} thrown in /var/www/html/bootstrap/autoload.php on line 17
```
